apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes/pingpong-depl.yaml

images:
  - name: IMAGE
    newName: artursreg.azurecr.io/pingpong:22dfc74cbb01ddb3a3c1f2a5d807a67924d31747