name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Check for ACR Password and Name.
    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin
    
    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.33.0
        inlineScript: |
          az login --service-principal -u 887f7420-def1-416b-8c68-c8615dce4cbe -p lYp8Q~BPaQbS9DDL4lpYJyOWyj0XpHTHndgeJcTJ --tenant 8caad09b-4487-48f9-b7d6-b47e22b2dd2f

    - name: Set custom Azure config directory
      run: |
        export AZURE_CONFIG_DIR=/tmp/.azure


    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/my-deployment my-container=${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }}
        kubectl rollout status deployment/my-deployment

      env:
        AZURE_CONFIG_DIR: /tmp/.azure
